### ISSUE TITLE
UE 5.8 compile failure: FJsonObject::Values keys are now UE::FSharedString

### ISSUE THREAD

**Issue by iNcredibleGM** [neely3d-rgb/ViewGen#3]
## Problem

The plugin does not compile against UE 5.8. A clean build fails with **27 errors** across four files, all from the same root cause.

## Cause

UE 5.8 changed `FJsonObject`'s key storage:

| | Key type |
|---|---|
| 5.7 and earlier | `TMap<FString, TSharedPtr<FJsonValue>>` |
| 5.8 | `TMap<UE::FSharedString, TSharedPtr<FJsonValue>>` |

Anywhere a `Values` loop key is used *as an `FString`* — a `TMap`/`TSet` lookup, `Contains`, `==`, `+`, or a `const FString&` parameter — no longer compiles.

```
error C2039: 'Contains': is not a member of 'UE::TSharedString<TCHAR>'
error C2664: cannot convert argument 1 from 'const T' to 'const FString &'
error C2678: binary '=='/'+' : no operator found which takes a left-hand operand of type 'const T'
error C2440/C2665: cannot convert from 'const T' to 'FString' (TMap/TSet Add, FindOrAdd)
```

## Where

| File | Functions | Sites |
|---|---|---|
| `ComfyNodeDatabase.cpp` | `ParseObjectInfo`, `ParseSingleNode` | 6 |
| `GenAIHttpClient.cpp` | `OnHistoryResponseReceived` | 1 |
| `GenAISettings.cpp` | `LoadPreset` | 1 |
| `SWorkflowGraphEditor.cpp` | `ExportStagedWorkflows`, `ExportWorkflowJSON`, `ImportWorkflowJSON`, `PasteFromSystemClipboard` | 12 |

## Reproduce

Build the plugin against UE 5.8 with no source changes.

### Build output

```text
Building UE58TryItEditor...

ComfyNodeDatabase.cpp(69,36): error C2039: 'Contains': is not a member of 'UE::TSharedString<TCHAR>'
        bool bIsAnthropicNode = Pair.Key.Contains(TEXT("Anthropic")) || Pair.Key.Contains(TEXT("Claude")) || ...
                                         ^
Engine/Source/Runtime/Core/Public/Containers/SharedString.h(30,7): note: see declaration of 'UE::TSharedString<TCHAR>'
class TSharedString
      ^

ComfyNodeDatabase.cpp(87,23): error C2664: 'FComfyNodeDef FComfyNodeDatabase::ParseSingleNode(const FString &, ...) const':
        cannot convert argument 1 from 'const T' to 'const FString &'

ComfyNodeDatabase.cpp(118,12): error C2665: 'TMapBase<KeyType,ValueType,SetAllocator,KeyFuncs>::Add':
        no overloaded function could convert all the argument types
        with
        [
            KeyType=FString,
            ValueType=FComfyNodeDef,
            SetAllocator=FDefaultSetAllocator,
            ...

GenAISettings.cpp(372,20): error C2665: 'TMapBase<KeyType,ValueType,SetAllocator,KeyFuncs>::Add':
        no overloaded function could convert all the argument types
        with
        [
            KeyType=FString,
            ValueType=FString,
            ...

GenAIHttpClient.cpp(2477,22): error C2440: 'initializing': cannot convert from 'const T' to 'FString'

SWorkflowGraphEditor.cpp(1339,30): error C2664: 'bool TSet<FString,...>::Contains(const FString &) const':
        cannot convert argument 1 from 'const T' to 'const FString &'

SWorkflowGraphEditor.cpp(5347,15): error C2665: 'TSet<FString,...>::Add':
        no overloaded function could convert all the argument types

SWorkflowGraphEditor.cpp(5963,24): error C2665: 'TMapBase<...>::Add':
        no overloaded function could convert all the argument types

SWorkflowGraphEditor.cpp(6366,25): error C2665: 'TMapBase<...>::FindOrAdd':
        no overloaded function could convert all the argument types

... 27 errors total

Result: Failed (OtherCompilationError)
```

<details>
<summary>Full error-code breakdown</summary>

| Code | Count | What it means here |
|---|---|---|
| `C2665` | 8 | `TMap`/`TSet`/`TArray` `Add` or `FindOrAdd` cannot convert the key |
| `C2039` | 6 | `'Contains'` is not a member of `UE::TSharedString<TCHAR>` |
| `C2440` | 5 | `cannot convert from 'const T' to 'FString'` |
| `C2664` | 4 | cannot convert argument 1 to `const FString &` |
| `C2679` | 2 | `binary '['` — no operator takes the key type |
| `C2678` | 2 | `binary '=='` / `binary '+'` — no operator for the key type |

</details>

## Suggested fix

Bind the key to a local `FString` before using it as one:

```diff
- FString FieldKey = Field.Key;
+ const FString FieldKey(Field.Key);
```

```diff
- FComfyNodeDef Def = ParseSingleNode(Pair.Key, *NodeInfoPtr);
+ const FString NodeKey(Pair.Key);
+ FComfyNodeDef Def = ParseSingleNode(NodeKey, *NodeInfoPtr);
```

This is version-agnostic: on engines where the key is already an `FString` the construction is a copy, so the same code compiles on 5.7 and 5.8 with no `#if` guard.

---

**Note:** the `TArray::Pop(false)` → `Pop(EAllowShrinking::No)` change from the same 5.8 pass is already in the repo, so this covers only the JSON key type. Thanks for fixing that one in #2.

---

### Environment

- Unreal Engine 5.8.0 (Win64, Development Editor, VS 2022)
- Windows 11
- ComfyUI 0.34.0 (vanilla, from source)
- Plugin: clean clone of `main` @ `cd29000`
